//------------------------------------------------------------------------------
// AssemblyInfo.cs
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------
using Microsoft.Dss.Core.Attributes;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;

using System.Reflection;
using Microsoft.Dss.Core;

[assembly: ServiceDeclaration(DssServiceDeclaration.ServiceBehavior)]
[assembly: interopservices.ComVisible(false)]
[assembly: AssemblyTitle("Maze Simulator Service (RA version)")]
[assembly: AssemblyProduct("Maze Simulator Service (RA version)")]
[assembly: AssemblyVersion("1.8")]
[assembly: AssemblyCopyright("Written by Trevor Taylor based on code from Ben Axelrod (Jul 2007). (RA version by Raul Arrabales).")]
[assembly: AssemblyDescription("Allows simple maze-like environments for be built for the Simulator. Built for MSRS V1.5. This version is freely available. (RA version uses SONAR instead of LRF).")]
[assembly: AssemblyCompany("Queensland University of Technology (RA version by www.Conscious-Robots.com)")]

