//------------------------------------------------------------------------------
// Generated by dssnewservice - Modified by Raul Arrabales - 03 Jul 07
//
// ARCOS SONAR SERVICE
//
// CRANIUM - Pioneer 3 DX Hardware Services - ARCOS SONAR
// This service provides access to P3DX frontal Sonar Array. 
// It subscribes to Microsoft ARCOS CORE Service. It offers subscriptions. 
// 
// This code is provided AS IS. No warranty is provided for any purpose. 
// Use it at your own risk. 
// Please notify bugs, suggestions to: raul@conscious-robots.com
//
//  $File: ArcosSonarTypes.cs $ $Revision: beta6 $
//------------------------------------------------------------------------------

using Microsoft.Ccr.Core;
using Microsoft.Dss.Core.Attributes;
using Microsoft.Dss.ServiceModel.Dssp;
using System;
using System.Collections.Generic;
using W3C.Soap;

using pxsonar = Microsoft.Robotics.Services.Sonar.Proxy;

namespace Cranium.Arcos
{
    
    /// <summary>
    /// ArcosSonar Contract
    /// </summary>
    public sealed class Contract
    {
        /// The Unique Contract Identifier for the ArcosSonar service
        public const String Identifier = "http://www.conscious-robots.com/2007/07/sonar.html";
    }

    public class Replace : Replace<pxsonar.SonarState, PortSet<DefaultReplaceResponseType, Fault>>
    {
    }

}
