//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Dss.Core.Attributes;
using System;
using System.Collections.Generic;
using interopservices = System.Runtime.InteropServices;
using System.Reflection;

[assembly: ServiceDeclaration(DssServiceDeclaration.ServiceBehavior)]
[assembly: interopservices.ComVisible(false)]


[assembly: AssemblyTitleAttribute("Arcos SONAR Service")]
[assembly: AssemblyDescriptionAttribute("Arcos SONAR Service")]
[assembly: AssemblyCompanyAttribute("www.Conscious-Robots.com")]
[assembly: AssemblyProductAttribute("CRANIUM")]
[assembly: AssemblyCopyrightAttribute("(c) 2007 Raul Arrabales")]
